### ISSUE TITLE
How do we enable this?

### ISSUE THREAD

**Issue by asos-nickbrown** [info-emait/QueryGantt#1]
I cannot find where to enable this after installation - can you provide some screenshots please? Thanks!

**Comment by info-emait** [comment]
Hi, if you are using Azure DevOps Server (on-premise) you need to click on your profile in the upper right corner, then select the **Manage features** option, and then just turn on the Query Gantt feature. The feature needs to be enabled per project.
![image](https://github.com/info-emait/QueryGantt/assets/102584517/e699cf46-bb33-4e7a-8cae-91a11f834790)

If you are using Azure DevOps Services you can follow the instructions described here https://learn.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops.

**Comment by asos-nickbrown** [comment]
For Azure DevOps Services this is not available in preview features using 'for me' OR 'for this organisation':

<img width="368" alt="Screenshot 2024-05-26 at 12 40 31" src="https://github.com/info-emait/QueryGantt/assets/125475818/5b59f51f-ae7e-42f9-984c-e38bf6b02d14">

<img width="371" alt="Screenshot 2024-05-26 at 12 40 23" src="https://github.com/info-emait/QueryGantt/assets/125475818/319918b8-2263-42c0-b0a8-10749725ed7c">

<img width="381" alt="Screenshot 2024-05-26 at 12 40 13" src="https://github.com/info-emait/QueryGantt/assets/125475818/422d25fe-721b-44db-9cc7-706dc3164457">

<img width="375" alt="Screenshot 2024-05-26 at 12 40 02" src="https://github.com/info-emait/QueryGantt/assets/125475818/c91c5c1c-1029-4378-a104-75ead9c77e60">

<img width="373" alt="Screenshot 2024-05-26 at 12 39 47" src="https://github.com/info-emait/QueryGantt/assets/125475818/a2fe1961-2979-48ea-b0b9-302cc04ed254">

Ticket should be reopened

**Comment by info-emait** [comment]
Hi Nick,

I just uploaded the new v1.1.1 version,  where the feature is enabled by default, so please, try to update (or uninstall and than install the extension), and you should be able to use the extension:

![image](https://github.com/info-emait/QueryGantt/assets/102584517/3792c642-7998-4856-87c5-3644895cb5e3)

**Comment by asos-nickbrown** [comment]
Thanks - I can see it now :) 

Is there any plan to make it a preview feature?
