### ISSUE TITLE
Question - how does the must have / should have / etc logic work?

### ISSUE THREAD

**Issue by asos-nickbrown** [info-emait/QueryGantt#4]
There aren't any fields for this in ADO - how does it come to the conclusion around what items are? Can it be disabled?

**Comment by asos-nickbrown** [comment]
Thanks :) 

Tbh, for our use case, we have feature teams working on their part of an overall epic, so the notion of must/should etc. isn't relevant for us. I wonder if it could be switched on rather than being a default view?

**Comment by info-emait** [comment]
Hi Nick,

thank you for your feedback. We are planning to add the ability to turn on/off the display of the priority to the next version.
