### ISSUE TITLE
Feature request: keep hex code colour of work item respective of the project

### ISSUE THREAD

**Issue by asos-nickbrown** [info-emait/QueryGantt#5]
We have a slightly flawed setup of linking Epic > Epic > Feature, where the first epic represents a 'Portfolio Epic' then relevant platforms link their Epic (as a child) to that portfolio epic. We want to use this extension to show the timeline of the child items. The portfolio epics have a different colour (green) compared to the epics underneath that:

![image](https://github.com/info-emait/QueryGantt/assets/125475818/ea867d72-0422-4e65-9aa3-61d6227408a3)

However, when doing a cross project query to get all the child items, the gantt chart retains the colour of the 'portfolio' epics:

![image](https://github.com/info-emait/QueryGantt/assets/125475818/c8de2eb9-a4ab-4d56-836c-34bffab68224)

**Comment by info-emait** [comment]
Hi Nick,

thank you for your feedback. We are planning to add the functionality which will ensure that the color and icon of the work items will be honored in the queries made across multiple projects to the next version.

**Comment by info-emait** [comment]
Hi Nick,

there is a new version of the QueryGantt extension out there, now the extension keeps icon and color of each work item respective of the project.
