### ISSUE TITLE
Feature request: Download as PNG/JPEG

### ISSUE THREAD

**Issue by asos-nickbrown** [info-emait/QueryGantt#6]
It would be great to be able to download as an image rather than an Excel file :)

**Comment by info-emait** [comment]
Hi Nick,

we are planning to add the ability to download the gantt as an png image to to the next version. Meanwhile you can use the browser's default **Take Screenshot** functionality.

**Comment by info-emait** [comment]
Hi Nick,

there is a new version of the QueryGantt extension out there, the requested feature is included and enables you to download the gantt as an png image.
