### ISSUE TITLE
XLSX Exports Only a Few Months

### ISSUE THREAD

**Issue by pdhenrique3** [info-emait/QueryGantt#9]
I've just installed this new Extension and I am loving it. However, I have a full year query, but when I Export it to XLS it only shows a Maximum of 13 weeks.

**Comment by info-emait** [comment]
Hi,

thank you for your feedback. In the next version, which will be out very soon, the exported xlsx file will contain predefined weeks which will cover the whole year. However, if you want to extend the excel file, all you need is to just select collumns for the last week, copy them and paste as the next new week.

![gantt-full-year](https://github.com/info-emait/QueryGantt/assets/102584517/60077c17-ac4d-4e08-b305-05029dcea128)
